apiVersion: v1
kind: Template
metadata:
  name: pbw-liberty-jenkins-pipeline
  annotations:
    openshift.io/display-name: Plants by WebSphere on Liberty Jenkins Pipeline
    description: Jenkins Pipeline for Plants by WebSphere on Liberty App
    tags: liberty,websphere,derby
    openshift.io/provider-display-name: Ernst & Young - Digital Emerging Technologies
    openshift.io/documentation-url: https://github.com/mikecai-ey/sample.plantsbywebsphere.git
parameters:
  - name: APP_NAME
    description: The name assigned to all of the application objects defined in this template.
    displayName: Application Name
    required: true
    value: pbw-liberty-derby-demo
  # - name: DEPLOYED_APP_NAME
  #   description: The name of the deployed application.
  #   displayName: Deployed Application Name
  #   required: true
  #   value: pbw-liberty-mariadb
  - name: PROJECT_NAME
    description: The name of the deployed project.
    displayName: Deployed Project Name
    required: true
    value: liberty-demo-pbw-jenkins-pipeline
  - name: GIT_SOURCE_URL
    description: The source URL for the application
    displayName: Source URL
    required: true
    value: https://github.com/mikecai-ey/sample.plantsbywebsphere.git
  - name: GIT_SOURCE_REF
    description: The source Ref for the application
    displayName: Source Ref
    required: true
    value: master
  - description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
    displayName: GitHub Webhook Secret
    from: "[a-zA-Z0-9]{40}"
    generate: expression
    name: GITHUB_WEBHOOK_SECRET
    required: true
  - description: A secret string used to configure the Generic webhook.
    displayName: Generic Webhook Secret
    from: "[a-zA-Z0-9]{40}"
    generate: expression
    name: GENERIC_WEBHOOK_SECRET
    required: true
objects:
  #################### ImageStrem ####################
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    #      namespace: liberty-demo-pbw-custom-deploy
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          referencePolicy:
            type: Local
  #################### BuildConfig ####################
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
      creationTimestamp: null
      labels:
        name: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      source:
        git:
          uri: "${GIT_SOURCE_URL}"
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
          env:
            - name: "GIT_SOURCE_URL"
              value: "${GIT_SOURCE_URL}"
            - name: "GIT_SOURCE_REF"
              value: "${GIT_SOURCE_REF}"
            - name: "APP_NAME"
              value: "${APP_NAME}"
            - name: "PROJECT_NAME"
              value: "${PROJECT_NAME}"
        type: JenkinsPipeline
      triggers:
        - github:
            secret: "${GITHUB_WEBHOOK_SECRET}"
          type: GitHub
        - generic:
            secret: "${GENERIC_WEBHOOK_SECRET}"
          type: Generic
  #################### DeploymentConfig ####################
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
          - name: ${APP_NAME}
            image: ${APP_NAME}:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 9080
              protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers: []
      # - type: ConfigChange 
      # - imageChangeParams:
      #     automatic: true
      #     containerNames:
      #     - pbw-liberty-derby-demo
      #     from:
      #       kind: ImageStreamTag
      #       name: sample.plantsbywebsphere:latest
      #   type: ImageChange
      strategy:
        type: Rolling
  #################### Service ####################
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    #      namespace: liberty-demo-pbw-custom-deploy
    spec:
      ports:
        - name: 9080-tcp
          port: 9080
          protocol: TCP
          targetPort: 9080
        - name: 9443-tcp
          port: 9443
          protocol: TCP
          targetPort: 9443
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP
  #################### Route ####################
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
#      namespace: liberty-demo-pbw-custom-deploy
    spec:
      port:
        targetPort: 9080-tcp
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      tls:
        termination: edge
      wildcardPolicy: None
