apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: pbw-liberty-derby-demo
  name: sample.plantsbywebsphere
  namespace: liberty-demo-pbw-custom-deploy
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    referencePolicy:
      type: Local